FROM linuxserver/code-server:amd64-4.4.0-ls127
# Instala el git 
RUN curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | bash -s lts
# Instala pm2 
RUN npm install -g pm2 @nestjs/cli
# Instala python 3.10
RUN set -eux; \
    apt update; \ 
    apt -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev; \
    wget https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tgz; \
    tar -xf Python-3.10.14.tgz; \
    cd Python-3.10.14; \
    ./configure --prefix=/usr/local --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"; \
    make; \
    make altinstall; \
    pip3.10 install --user --upgrade pip 
#Instala docker cliente
RUN set -eux; \
    apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common; \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -; \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"; \
    apt-get update; \
    apt-get -y install docker-ce
