version: '3.8'

services:
  gpaxgantt:
    image: infowarecr/gpax_gantt
    environment:
      - host=gpax1
    command: ["node", "gantt.js"]
    networks:
      - host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  host:
   external: true