version: '3.8'

services:
  gpaxapi:
    image: infowarecr/gpax:20240304
    environment:
      - host=gpax1
    command: ["node", "gpax.js"]
    networks_mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
