version: '3.8'

services:
  gpaxapi:
    image: infowarecr/gpax:latest
    command: ["node", "gpax.js"]
    networks_mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
